Music_Sharing_Portal/Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'

urlpatterns = [
    path('', views.index, name='index'),  # url for file uploading
    path('public/', views.public_audio_files, name='public_files'),
    path('private/', views.private_audio_files, name='private'),
    path('protected/', views.protected_audio_files, name='protected'),
    path('download/<int:file_id>/', views.download_file, name='download_file'),
    path('delete/<int:file_id>', views.delete_file, name='delete'),
    path('delete/protected/<int:file_id>', views.delete_file, name='protected_delete'),
    path('delete/<int:file_id>/<int:user_id>', views.delete_file, name='public_delete'),
]

Music_Sharing_Portal/Music_Sharing_Portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('home/', include('Home.urls')),
    path('verification/', include('verify_email.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music_Sharing_Portal/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('verify/<auth_token>', views.verify, name='verify'),
    path('success/', views.success, name='success'),
    path('verification-error/', views.error, name='error'),
]

Music_Sharing_Portal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/custom.css" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

Music_Sharing_Portal/templates/error.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register {% endblock %}
{% block content %}
<div class="container" style="display:flex;justify-content:center;align-items:center;height:100vh;">
    <div class="row" style="text-align: center;">
        <div class="col-12">
            <div class="card" style="padding:30px;width:250px;">
                <h1 style="text-align:center;">Error!!</h1><br>
                <a href="{% url 'authentication:login' %}"><button class="btn btn-secondary">Go Back</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Music_Sharing_Portal/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Index {% endblock %}
{% block content %}

<div class="fluid-container" style="height:fit-content;min-height:100vh;">
<!--    Navbar    -->
    <nav class="navbar index-nav">
        <a class="navbar-brand" href="" ><b>Music Sharing Portal</b></a>
        <div>
            {% if user.is_authenticated %}
            <button class="btn btn-primary">{{user.first_name}}</button>
            {% endif %}
            <a href="{% url 'authentication:logout' %}"><button class="btn btn-primary nav-btn">Logout</button></a>
        </div>
    </nav>

<!--   music upload section  -->

    <div class="row hero-row mt-3">
        <div class="col-sm-12 col-md-4 col-lg-4">
            <div class="shadow card" style="margin-left:20px;border-radius:10px;">
                <div class="card-body">
                    <div class="card-title">
                        <h3 class="card-h">Upload Files Here</h3>
                        {% if user.is_authenticated %}
                            <form method="POST" action="{% url 'Home:index' %}" enctype="multipart/form-data">
                                {% csrf_token %}

                                <div class="form-group upload-card-margin">
                                    <label for="filename">File name:</label>
                                    <input type="text" class="form-control" id="filename" name="file_name" required>
                                </div>
                                <div class="form-group upload-card-margin">
                                     <label for="file">File:</label>
                                    <input type="file" class="form-control" id="file" accept=".mp3" name="file" required>
                                </div>
                                <div class="form-group upload-card-margin">
                                     <label for="file_image">Image:</label>
                                    <input type="file" class="form-control" id="file_image" accept=".png" name="file_image" required>
                                </div>
                                <div class="form-group upload-card-margin">
                                     <label for="visibility">Visibility:</label>
                                    <select class="form-control" id="visibility" name="visibility" required>
                                        <option value="public">--Select visibility type--</option>
                                        <option value="public">Public</option>
                                        <option value="private">Private</option>
                                        <option value="protected">Protected</option>
                                    </select>
                                </div>
                                <div class="form-group upload-card-margin" style="display: none;" id="p_email">
                                     <label>Email(user who need access):</label>
                                    <input type="text" class="form-control"  name="p_email">
                                </div>
                                <a href="{% url 'Home:index' %}"><button type="submit" class="btn btn-primary" >UPLOAD</button></a>
                            </form>
                        {% endif %}
                        <br>
                        {% for i in messages %}
                            <div class="alert">
                                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                                {{i}}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


<!--        files display section-->


        <div class="col-sm-12 col-md-8 col-lg-8">
            <div class="shadow card" style="margin-right:20px;border-radius:10px;">
                <div class="card-body">

                    <!--     Public files section-->

                    <a href="{% url 'Home:public_files' %}" style="text-decoration:none;"><h4 class="file-card">Public files </h4></a>
                    <hr>
                    <div class="row">
                    {% for i in public_files %}
                        <div class="col-sm-6 col-lg-3 col-md-3">
                            <div class=" shadow card h-60 mb-3 mt-3" style="border-radius:10px;text-align:center;">
                                <img class="card-img-top" src="{{ i.file_image.url }}" height="150px;">
                                <div class="card-body">
                                    <div class="card-title">
                                        <p class="file_name">{{i.file_name}}</p><br>
                                        <div class="row">
                                            <div class="col-6">
                                                <a href="{% url 'Home:download_file' i.id %}"><i class="fa fa-play-circle" style="font-size:48px;color:blue;"></i></a>
                                            </div>
                                            <div class="col-6" style="display:flex;justify-content:right;align-items:center;">
                                                {% if user.is_authenticated %}
                                                <a href="{% url 'Home:public_delete' i.id user.id %}"><i class="fa fa-trash" style="font-size:25px;"></i></a><br>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>

                    <!--     Private files section-->

                    <a href="{% url 'Home:private' %}" style="text-decoration:none;"><h4 class="file-card">Private files </h4></a>
                    <hr>
                    <div class="row">
                        {% for i in private_files %}
                        <div class="col-sm-6 col-lg-3 col-md-3">
                            <div class="shadow card h-80 mb-3 mt-3" style="border-radius:10px;">
                                <div class="card-body">
                                    <img class="card-img-top" src="{{ i.file_image.url }}" width="100px;">
                                    <div class="card-title">
                                        <p class="file_name">{{i.file_name}}</p><br>
                                        <div class="row">
                                            <div class="col-6">
                                                <a href="{% url 'Home:download_file' i.id %}"><i class="fa fa-play-circle" style="font-size:48px;color:green"></i></a>
                                            </div>
                                            <div class="col-6" style="display:flex;justify-content:right;align-items:center;">
                                                <a href="{% url 'Home:delete' i.id %}"><i class="fa fa-trash" style="font-size:25px;"></i></a><br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>

                    <!--     Protected files section-->

                    <a href="{% url 'Home:protected' %}" style="text-decoration:none;"><h4 class="file-card">Protected files</h4></a>
                    <div class="row">
                        {% for i in protected_files %}
                        <div class="col-sm-6 col-lg-3 col-md-3">
                            <div class="shadow card h-80 mb-3 mt-3" style="border-radius:10px;">
                                <img class="card-img-top" src="{{i.file_image.url}}">
                                <div class="card-body">
                                    <div class="card-title">
                                        <p class="file_name">{{i.file_name}}</p><br>
                                        <div class="row">
                                            <div class="col-6">
                                                <a href="{% url 'Home:download_file' i.id %}"><i class="fa fa-play-circle" style="font-size:48px;color:green"></i></a>
                                            </div>
                                            <div class="col-6" style="display:flex;justify-content:right;align-items:center;">
                                                <a href="{% url 'Home:protected_delete' i.id %}"><i class="fa fa-trash" style="font-size:25px;"></i></a><br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  // JavaScript for showing email input field when protected option is selected

  const    visibility = document.getElementById('visibility');
  const p_email = document.getElementById('p_email');

  visibility.addEventListener('change', function() {
    if (visibility.value === 'protected') {
      p_email.style.display = 'block';
    } else {
      p_email.style.display = 'none';
    }
  });
</script>

{% endblock %}

Music_Sharing_Portal/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login {% endblock %}
{% block content %}
<div class="container auth-container">
    <div class="col-lg-6">
        <div class="shadow cards" style="padding:50px;border-radius:10px;">
        <h2 class="auth-title">LOGIN FORM</h2>
    <form method="POST">
    {% csrf_token %}

      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" name="username" required>
      </div>

      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" required>
      </div>
        <br>

      <button type="submit" class="btn btn-primary">Login</button>
    </form><br>
       <p>Dont have an account?<a href="{% url 'authentication:register' %}">register here</a></p><br>
            {% for i in messages %}
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{i}}
            </div>
            {% endfor %}
    </div>
        </div>
</div>
{% endblock %}

Music_Sharing_Portal/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register {% endblock %}
{% block content %}
<div class="container auth-container">
    <div class="col-lg-6">
        <div class="shadow cards" style="padding:50px;border-radius:10px;">
        <h2 class="auth-title">REGISTRATION FORM</h2>
    <form method="POST">
    {% csrf_token %}

      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" id="username" name="username" required>
      </div>

      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" name="email" required>
      </div>

      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" required>
      </div>

      <div class="form-group">
        <label for="confirm_password">Confirm Password:</label>
        <input type="password" class="form-control" id="confirm_password" name="password1" required>
      </div>
        <br>

        <button type="submit" class="btn btn-primary" style="width:100%;">Register</button>
    </form><br>
            <a href="{% url 'authentication:login' %}"><button type="submit" class="btn btn-primary" style="width:100%;">Login</button></a>
        {% for i in messages %}
        {{i}}
        {% endfor %}
    </div>
        </div>
</div>
{% endblock %}

Music_Sharing_Portal/templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register {% endblock %}
{% block content %}
<div class="container" style="display:flex;justify-content:center;align-items:center;height:100vh;">
    <div class="row" style="text-align: center;">
        <div class="col-12">
            <div class="shadow card" style="padding:30px;width:500px;">
                <h3 style="text-align:center;color:blue;">Verify your email</h3><br>
                <p style="font-family:verdana;">Verification link has been sent to provided mail address...</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}